# Generated by Django 2.2 on 2020-09-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(db_index=True, max_length=233, verbose_name='商品'),
        ),
    ]
