# Generated by Django 2.2 on 2020-09-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tmodel', '0003_auto_20200918_1443'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='good',
            unique_together=set(),
        ),
    ]
